config/routes.rb
Rails.application.routes.draw do

  root 'employees#home'
  
  resources :employees
  resources :clients
  resources :sites
  resources :service1s
  
  get 'addemployee', to: 'employees#new'
  get 'addclient', to: 'clients#new'
  get 'addsite' , to: 'sites#new'
  get 'addservice', to: 'service1s#new'
  get 'showmap', to: 'location#index'
  get 'contact', to: 'employees#contact'
  get 'about', to: 'employees#about'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 # get :SessionsController, :full => true
 resources :sessions do
  get :autocomplete_employee_username, :on => :collection  #:full => true
end

  
end

app/models/employee.rb
class Employee < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :contact, presence: true, length: { maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 50 }
  
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def home
  end
  
  def new
    @employee = Employee.new
  end
  
  def show
    @employee = Employee.find(params[:id])
  end
  
  def create
    @employee =Employee.new(employee_params)
    if user.save
      flash[:success] = "Employee added into the system"
      redirect_to @employee
    else
      render root_path
    end
  end
  
  private
  
  def employee_params
      params.require(:employee).permit(:name, :address, :contact, :email, :username, :password,
                                   :password_confirmation)
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :logged_in_employee, only: [:edit, :update]

  def home
  end
  
  def index
    @employees=Employee.all
  end
  
  def new
    @employee = Employee.new
  end
  
  def show
    @employee = Employee.find(params[:id])
  end
  
  def create
    @employee =Employee.new(employee_params)
    if @employee.save
      flash[:success] = "Employee added into the system"
      redirect_to employees_path
    else
      render 'new'
    end
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end
  
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(employee_params)
            flash[:success] = "Employee updated"
      redirect_to @employee
    else
      render 'edit'
    end
  end
  
  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to employees_url
  end
  
  private
  
  def employee_params
      params.require(:employee).permit(:name, :address, :contact, :email, :username, :password,
                                   :password_confirmation)
  end
  
  def logged_in_employee
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
  
  def correct_user
      @employee = Employee.find(params[:id])
      redirect_to(root_url) unless current_employee?(@employee)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def gravatar_for_employee(employee)
    gravatar_id = Digest::MD5::hexdigest(employee.full_name)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: employee.name, class: "gravatar")
  end
end

app/views/employee/new.html.erb
<% provide(:title, 'Add Employee') %>
<h1>Add Employee</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(employee_index_url) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :address %>
      <%= f.text_field :address %>
      
      <%= f.label :contact %>
      <%= f.text_field :contact %>

      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Add employee to the system", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employee/show.html.erb
<% provide(:title, @employee.name) %>
<h2> Hi, <%= @employee.name %></h2>
<h2>Current Time is <%= Time.zone.now %> </h2>

<div class="tab">
  <button class="tablinks" onclick="openTask(event, 'Add Client')">Add Client</button>
  <button class="tablinks" onclick="openTask(event, 'Food Pantry')">Food Pantry</button>
  <button class="tablinks" onclick="openTask(event, 'Shelter')">Shelter</button>
</div>

<div id="Add Client" class="tabcontent">
  <h3>Add Client</h3>
  <p>Add client details into the system.
  <form class="form-wrapper">
    <input type="text" id="tags" placeholder="Search for..." required>
    <input type="submit" value="go" id="submit">
  </form>
  </p>
</div>

<div id="Food Pantry" class="tabcontent">
  <h3>Food Pantry</h3>
  <p>Add the food services used by the client.</p> 
</div>

<div id="Shelter" class="tabcontent">
  <h3>Shelter</h3>
  <p>Add the shelter services used by the client.</p>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
function openTask(evt, taskName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(taskName).style.display = "block";
    evt.currentTarget.className += " active";
}

$( function() {
    var availableTags = [
     "Bhavin",
     "Bob",
     "Bradley",
     "Shwetha",
     "john",
     "ruby",
     "Rails"
    ];
      $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
</script>