config/routes.rb
Rails.application.routes.draw do

  root 'employees#home'
  
  resources :employees
  resources :clients
  resources :sites
  resources :service1s
  
  get 'addemployee', to: 'employees#new'
  get 'addclient', to: 'clients#new'
  get 'addsite' , to: 'sites#new'
  get 'addservice', to: 'service1s#new'
  get 'showmap', to: 'location#index'
  get 'contact', to: 'employees#contact'
  get 'about', to: 'employees#about'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 # get :SessionsController, :full => true
 resources :sessions do
  get :autocomplete_employee_username, :on => :collection  #:full => true
end

  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
     <ul>
       <li> <%= link_to "About", about_path %></li>
       <li> <%= link_to "Contact", contact_path %></li>
     </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Serve the people", '#', id: "logo" %>
        <li>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Find My Place",   showmap_url %></li>
            <% if logged_in? %>
            <li><%= link_to "Give Service",   addservice_url %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Add <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Employee", addemployee_url %></li>
              <li><%= link_to "Add Site", addsite_url %></li>
              <li><%= link_to "Add Client", addclient_url %></li>
              
              <li class="divider"></li>
            </ul>
            </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Show <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Show Employees", employees_url %></li>
              <li><%= link_to "Show Sites", sites_url %></li>
              <li><%= link_to "Show Clients", clients_url %></li>
              <li><%= link_to "Show Services", service1s_url %></li>
              <li class="divider"></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Update <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Employee", edit_employee_url(current_employee) %></li>

              <li class="divider"></li>
            </ul>
            </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_employee %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | App to manage food and shelter services</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'  %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>